namespace:
  name: demo
 
image:
  repository: nginx
  tag: alpine
  pullPolicy: ifNotPresent 

replicaCount: 3

resources:
  requests:
    memory: 256Mi
    cpu: 50m

service:
  port: 8111
  type: ClusterIP

configmap:
  data: "version: alpine"
