namespace:
  name: demo
 
image:
  repository: nginx
  tag: alpine
  imagePullPolicy: ifNotPresent 

replicaCount: 3

resources:
  requests:
    memory: "256Mi"
    cpu: "50m"

spec:
  ports:
  - port: 8111
    protocol: TCP
    targetPort: 8111
  selector:
    app: nginx
    tag: alpine
  type: ClusterIP

data:
  version: alpine
kind: ConfigMap
