namespace:
  name: staging

service:
  port: 8111
  type: ClusterIP
 
image:
  repository: nginx
  tag: 1.18.0
  pullPolicy: ifNotPresent 

replicaCount: 1

resources:
  requests:
    memory: 128Mi
    cpu: 50m

spec:
  ports:
  - port: 8111
    protocol: TCP
    targetPort: 8111
  selector:
    app: nginx
    tag: alpine
  type: ClusterIP

configmap:
  data: "versionL 1.18.0"
