namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

ports:
  protocol: TCP

livenessProbe:
  path: /healthz
  port: 3111

readinessProbe:
  path: /healthz
  port: 3111

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    memory: 128Mi
    cpu: 500m
